const text = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut gravida tellus sed justo dictum iaculis. Nulla diam tellus, efficitur non dui a, venenatis interdum arcu. Aliquam vitae tortor aliquam, blandit justo a, auctor justo. Nullam fringilla sed lacus ultricies suscipit. Aliquam condimentum neque orci, at molestie nulla tincidunt sit amet. Nunc pulvinar interdum elit et volutpat. Proin nec aliquet neque. Etiam elementum, risus nec ornare dignissim, diam nisl dignissim augue, non fringilla ipsum turpis et sem. Vivamus ut facilisis sapien. Mauris eu ullamcorper lectus, egestas dictum mauris.",
  "Morbi odio erat, bibendum et augue sit amet, malesuada pulvinar ipsum. Proin porttitor mattis tellus, iaculis eleifend lectus mattis id. Fusce sollicitudin neque mi, non porttitor mauris posuere sit amet. Maecenas in fringilla est, sed vehicula enim. Vestibulum elementum neque lacus, et condimentum massa tincidunt in. Integer ut luctus urna. Duis ac iaculis quam, sed pretium lectus. Aliquam laoreet consectetur arcu, at aliquam ante condimentum vitae. Nullam ac purus mauris. Quisque quis elit quam. Sed cursus augue eu lectus sollicitudin tempus. Nulla facilisi. Curabitur interdum lectus nisl, sit amet maximus magna suscipit eu. Vivamus fermentum, magna quis tincidunt vehicula, eros mauris elementum massa, a tempor ligula tellus at nisi.",
  "Nulla iaculis ipsum aliquet tortor porta, id mollis felis mattis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam vitae dui tempus tellus egestas elementum sed id diam. Cras dolor purus, semper et eros eget, fringilla cursus sapien. Maecenas non risus at libero commodo congue non eu metus. Nunc hendrerit libero quis odio vulputate, at gravida tellus molestie. Sed et placerat nulla. Nam consequat ullamcorper est eget semper. Sed cursus tortor ut arcu molestie, eget gravida erat mollis. Proin ligula sapien, aliquet quis interdum in, rhoncus at arcu. Cras mattis nec massa in malesuada.",
  "Cras posuere mi ante, eu eleifend mi luctus sit amet. Nulla vel vestibulum tellus. Vivamus blandit sapien eget augue vulputate tempor. Nulla ornare felis ut elit maximus, quis efficitur orci tempor. Donec dapibus sem ut ante lobortis, vitae luctus massa rutrum. Sed pellentesque, urna nec tristique consequat, risus massa viverra mi, quis interdum purus risus sed elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis aliquet eu odio a scelerisque.",
  "Fusce sed justo in velit ultricies imperdiet. Aliquam congue convallis nisi, ut ultricies metus blandit eget. Mauris nec eleifend urna. Nam a eros ac nunc mattis semper sed quis diam. Aliquam semper nulla vel sapien ultrices, eu commodo libero fermentum. Nam sollicitudin id lorem nec ultricies. Nulla at pulvinar justo. Ut consequat eros sit amet tincidunt porttitor. In hac habitasse platea dictumst. Cras condimentum bibendum tortor, vel tincidunt purus imperdiet faucibus. Integer erat nisi, consequat nec sapien sit amet, maximus vehicula ipsum. Nam elit felis, malesuada malesuada volutpat quis, pharetra eu sapien.",
  "In tellus quam, rhoncus ut quam at, aliquam gravida odio. Vestibulum malesuada sollicitudin vulputate. Sed cursus dolor et ante imperdiet tincidunt. Aenean a dignissim diam, quis molestie ex. Suspendisse potenti. Aliquam facilisis, erat quis posuere consectetur, mi metus aliquam justo, ut molestie nulla risus ullamcorper arcu. Aenean ullamcorper, elit vel viverra aliquam, justo eros auctor diam, id tempus risus augue eu ex. Ut blandit ante a semper efficitur. Fusce blandit tortor et nisi tempus, dapibus lobortis tellus molestie.",
  "Donec ac fringilla turpis. Nam sollicitudin odio eros, id lobortis tortor lobortis mollis. Quisque eget turpis eros. Nam elit orci, feugiat eu lacinia id, commodo id ante. Donec leo nisi, tempus sed scelerisque sodales, ultricies eu elit. Curabitur nec ipsum dictum, suscipit dui a, elementum nulla. Nam tempor augue nisi, eget suscipit lacus facilisis a. Suspendisse vitae mauris congue, congue dui eu, vestibulum nibh. Etiam eget purus at metus vulputate blandit. Fusce dapibus dolor vel ligula imperdiet, id mollis enim rutrum. Curabitur accumsan tortor non ullamcorper elementum. Curabitur at dapibus lorem, sit amet dignissim nisl. Sed dapibus, metus ac dictum pharetra, neque eros hendrerit nisi, sed suscipit est metus quis lorem. Praesent massa quam, rutrum vitae hendrerit vitae, consectetur in nisi. Duis in lacus in massa placerat vehicula.",
  "Donec id est quis sapien rutrum mattis non a urna. Curabitur aliquam metus vitae lectus pulvinar tristique eu ac neque. Fusce pretium quis odio ac elementum. Proin commodo quam libero. Etiam rhoncus rutrum condimentum. Pellentesque blandit augue semper purus auctor, consequat dictum ligula sollicitudin. Pellentesque facilisis libero et sem eleifend blandit. Donec et elit eget ligula congue elementum. Sed vel nibh odio. Sed ac consectetur neque, laoreet rutrum ex. Vestibulum eros dui, elementum sit amet vulputate et, congue a ex. Quisque a magna in nulla viverra tincidunt tempus at nibh.",
  "Quisque quis varius ex. Integer a ligula malesuada, suscipit urna eu, euismod urna. Integer sed tortor bibendum, facilisis felis quis, porta arcu. Phasellus vitae erat dolor. Quisque metus lectus, ultricies quis odio id, ornare eleifend augue. Cras at metus vitae sem suscipit maximus. Sed a tempor felis. Duis hendrerit interdum ex, nec pretium nibh ornare vitae. Nunc aliquet neque quis gravida consectetur. Fusce mollis, elit sit amet malesuada fringilla, est tortor ultricies leo, vitae cursus urna elit eget risus.",
  "Vivamus augue dui, condimentum ut ligula vel, condimentum rhoncus augue. Pellentesque nisi dolor, bibendum vitae finibus non, iaculis quis felis. Maecenas euismod dapibus lectus, quis lobortis nunc vehicula ac. In euismod efficitur ante nec varius. Nullam sed diam ultricies, imperdiet erat eu, semper felis. Proin quis lorem condimentum, pellentesque risus vitae, feugiat enim. Vestibulum porttitor feugiat nisi sit amet rutrum. Etiam dictum at lectus non vestibulum. Maecenas dictum massa sed porttitor dignissim. Nullam porta tempor ipsum, vitae porta nulla suscipit et. Sed sit amet ex quis est consequat tempor sed mollis neque. Nullam sit amet luctus magna, a imperdiet libero. Pellentesque sit amet massa diam. Duis quis elit vitae tortor aliquam facilisis. Aliquam sollicitudin ultricies mollis.",
  "Aliquam quis nibh dapibus, gravida ipsum at, venenatis velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus finibus quis nunc id fringilla. Pellentesque ultricies imperdiet efficitur. Nulla efficitur ligula faucibus semper malesuada. Proin eget purus ac lectus tempus efficitur. Nam luctus leo in scelerisque rhoncus.",
  "Mauris cursus sapien odio, nec sagittis arcu consectetur sed. Donec at fermentum metus. Vivamus maximus dignissim arcu, vitae finibus augue rutrum vitae. Donec et viverra mi. Fusce et mi dolor. Pellentesque ultricies varius est, quis pulvinar urna commodo ut. In vehicula et felis at feugiat. Donec metus metus, tempus id velit in, iaculis faucibus eros.",
  "Aliquam faucibus eros nec malesuada mollis. Suspendisse leo quam, commodo nec tortor eu, feugiat imperdiet ligula. Nam commodo dui nec tortor efficitur, sed efficitur justo facilisis. Proin aliquet risus in suscipit eleifend. Vestibulum non ex tincidunt, commodo dolor consectetur, efficitur dui. In scelerisque et neque quis aliquet. Sed ut lorem tempor, iaculis est id, posuere felis. Proin rhoncus tempor dui sed tincidunt. Sed et ornare felis. Vivamus vulputate porta ex mollis bibendum. Donec eget faucibus erat. Ut faucibus sem risus. Sed id metus posuere, sagittis tortor in, scelerisque dolor. Duis a mauris dui. Phasellus egestas est eros, in bibendum nisl sodales vel.",
  "Sed egestas ipsum tortor, et semper orci luctus sed. Cras elit ex, convallis at lectus maximus, venenatis efficitur nulla. Nulla facilisi. Sed egestas metus tellus, vitae luctus felis suscipit vitae. In odio tellus, iaculis ut nibh ut, molestie sodales risus. Sed dictum odio vitae ligula aliquam mollis. In a ex orci. Praesent nec massa at felis feugiat porta. Duis rutrum ligula nec cursus cursus. Maecenas cursus posuere nulla at suscipit. Pellentesque eget consectetur tortor. Maecenas elementum sodales lorem, sed semper nisl ullamcorper vel. Etiam felis nulla, bibendum eget efficitur eu, auctor vestibulum ipsum. In ornare, nisl ac semper fringilla, felis libero lobortis justo, ut efficitur dolor nulla sit amet dui. In hac habitasse platea dictumst.",
  "Suspendisse iaculis nisi sit amet augue pharetra, vitae faucibus orci dignissim. Aenean laoreet nisi id dolor volutpat luctus congue auctor mi. Sed blandit, nisi eget scelerisque porttitor, justo mauris congue ipsum, vitae varius urna nunc at nisl. Praesent condimentum eleifend porttitor. Integer placerat eget ligula dignissim cursus. Ut sodales, metus a ultricies condimentum, est augue efficitur dolor, eu consectetur nunc metus ac lacus. Integer gravida enim sit amet augue consequat semper. Nullam molestie lobortis fringilla. Nulla facilisi. Donec convallis dolor sapien. Phasellus pulvinar urna quis nisl consectetur, sed volutpat nunc sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas euismod augue vel imperdiet placerat. Ut purus tellus, malesuada et felis nec, malesuada sagittis dui. Maecenas ac massa vel magna viverra mattis. Pellentesque imperdiet molestie ligula in ultricies.",
  "Vestibulum a pellentesque enim. Cras imperdiet ipsum in pulvinar placerat. Praesent nibh velit, rutrum in mauris non, tempor venenatis felis. Nunc venenatis ante eget tortor malesuada consectetur. In hac habitasse platea dictumst. Vestibulum interdum dictum elit eu molestie. Donec eget arcu fringilla, porta nisl id, tempor nisl. Aenean a facilisis enim. Mauris tristique orci ac venenatis fermentum. Donec interdum nibh at metus consequat, eu auctor neque maximus. Curabitur ullamcorper sagittis augue id varius. Praesent sed ultrices est, vitae ornare erat.",
  "Morbi facilisis, ante eu rutrum tempor, enim lorem elementum nunc, tempor aliquet justo leo in arcu. Nulla facilisi. Fusce fringilla suscipit massa, sit amet aliquet mauris porta nec. Integer mattis, nisi a convallis aliquet, nulla odio eleifend erat, eu iaculis risus nisl a dolor. Integer sit amet egestas magna. Duis et nisl a lectus ultricies bibendum. Proin ac pulvinar tortor, vel elementum nisi. Cras nec lacus mattis magna porta efficitur. Sed vehicula condimentum purus, nec gravida ligula congue in.",
  "Sed eros lacus, tristique sed placerat id, egestas non ante. Nam erat ipsum, sodales ac neque non, bibendum rutrum arcu. Phasellus vel odio dapibus nunc luctus finibus. Sed vel finibus justo. Nam turpis felis, lobortis non lacus nec, imperdiet vulputate est. Mauris in facilisis nibh. Phasellus aliquam sapien quis ultricies commodo. Phasellus convallis eros quis tellus consequat scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum consectetur malesuada metus, vitae convallis nisl elementum in.",
  "In odio risus, consequat eu venenatis at, elementum vel orci. Integer in sem porta, tristique mauris quis, cursus nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt et nunc sed dictum. Sed vestibulum leo ornare, auctor tortor vitae, mollis nibh. Etiam dolor augue, ultrices vitae consequat non, rhoncus et lectus. Maecenas eleifend in sapien nec suscipit. Aenean quis semper magna. Nunc a condimentum quam. Donec non luctus sem. Donec tempor, erat sit amet ornare elementum, sapien quam dapibus purus, a tincidunt tortor lectus at purus. Pellentesque at metus iaculis, porta mi id, tincidunt urna. Sed id eros sit amet enim varius tempor nec ac felis. Quisque condimentum iaculis tincidunt. Phasellus ac mattis purus.",
  "Suspendisse potenti. Morbi ex nibh, ultricies sed libero fermentum, scelerisque rhoncus mi. Nullam ligula neque, feugiat eu pretium nec, aliquet et massa. Pellentesque sagittis, mauris sit amet tincidunt tincidunt, eros risus volutpat nulla, id blandit velit felis sit amet justo. Aenean vitae pulvinar nunc. Sed nisl odio, convallis at massa at, auctor luctus est. Donec faucibus, mauris eget rhoncus fringilla, ante ipsum ornare magna, nec posuere libero magna sit amet lacus.",
  "Nam congue lorem id sapien volutpat tempus. Curabitur sodales tortor hendrerit leo luctus maximus. In posuere arcu bibendum, scelerisque nisl vitae, accumsan urna. Donec tincidunt est arcu, sed pretium orci gravida vestibulum. Donec et ullamcorper augue. Aenean congue sapien ex, a vestibulum tellus condimentum sit amet. Vestibulum magna lorem, sodales efficitur dapibus ac, dignissim nec arcu. Cras velit eros, vehicula sed justo in, dignissim interdum lorem.",
  "Sed eu suscipit orci. Sed bibendum orci eu leo molestie, at aliquam dolor rhoncus. Morbi sagittis scelerisque mauris sed gravida. Nunc venenatis, quam eget faucibus imperdiet, metus justo fermentum libero, ullamcorper efficitur nulla mi at lectus. Nulla velit diam, tristique id elementum at, ornare nec leo. Maecenas sagittis nisl dictum nisi interdum tristique. Donec maximus sagittis molestie. Nulla laoreet nulla vitae eleifend mattis. Nullam elit dolor, convallis id elit eu, luctus fermentum augue. Phasellus vel diam nec dui varius tempus non id neque. Duis eleifend, quam id scelerisque cursus, ipsum ex varius neque, nec ornare augue erat sed lorem. Proin varius lectus et tellus fringilla, nec aliquam dui mattis. Duis dignissim massa eu sem blandit, ut tincidunt quam tempus. Aliquam aliquet at enim vel porttitor. Nulla pulvinar, dui et pretium sollicitudin, orci risus euismod ipsum, et rutrum mauris neque in nisl.",
  "Duis hendrerit auctor est, quis scelerisque ligula facilisis ut. Suspendisse potenti. Suspendisse potenti. Donec magna tortor, rutrum a volutpat non, placerat vel arcu. Nulla condimentum, nisi id mollis iaculis, eros ante maximus diam, non tincidunt mauris est eget arcu. Nunc pulvinar justo at lacus feugiat vulputate. Integer in dui sit amet ligula elementum aliquet. Ut id laoreet orci. Nullam nibh nulla, congue in arcu in, dignissim vulputate nunc. Aenean euismod diam leo, sit amet varius lacus volutpat vel. Fusce vehicula maximus consectetur. Proin vitae nulla cursus, lacinia mi pellentesque, convallis odio. Donec dapibus, ante vel cursus egestas, lectus lacus posuere nunc, eget cursus libero risus sit amet tellus.",
  "Donec eleifend eu purus in pharetra. Nunc at ultrices mauris, ac dapibus nunc. Curabitur gravida orci sed dolor finibus rhoncus. Nam auctor dui vestibulum turpis commodo, quis cursus felis pulvinar. Proin vestibulum ut nulla quis scelerisque. Ut sodales sagittis metus, vel commodo erat ornare sed. Duis faucibus mi velit, sed consectetur nisi cursus quis. Nulla elementum, leo ac pharetra vestibulum, tortor augue semper dui, sed feugiat tellus orci at orci. In hac habitasse platea dictumst.",
  "Praesent porttitor malesuada enim. Vivamus eget rutrum leo. In eu nunc sit amet nisl luctus placerat. Cras rhoncus dignissim auctor. Vivamus eget lectus mi. Nulla sapien magna, rhoncus vel eros eu, ultricies rhoncus nisl. Vestibulum iaculis orci metus, non laoreet velit fringilla ut. Phasellus cursus, tortor eu dignissim ultrices, libero tortor mollis nisi, ac tincidunt risus est ut mauris. Suspendisse potenti. Suspendisse at venenatis orci. Praesent a iaculis mauris, et eleifend enim.",
  "Vestibulum eget interdum turpis, ac varius magna. Nulla libero tellus, accumsan sed sapien id, viverra imperdiet sem. Aliquam vitae sagittis ipsum. Morbi ac ante molestie, aliquam risus sagittis, lobortis orci. Duis convallis lectus vitae volutpat sollicitudin. Aenean nisi erat, rutrum ut magna eget, commodo iaculis ex. Ut felis orci, porttitor ut metus at, tempus auctor libero. Fusce sit amet dictum nulla, et eleifend libero.",
  "Pellentesque pretium dui augue, a iaculis nunc sagittis ac. Phasellus vitae massa tempus, iaculis orci ut, tempor augue. Phasellus sem ante, bibendum nec posuere sit amet, tristique eu lectus. Nullam tristique consectetur tortor at ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed ac velit sed diam aliquet mattis in et neque. Suspendisse est sem, lacinia sit amet dolor non, convallis rhoncus tellus. Donec ut libero ante.",
  "Etiam a lobortis arcu. Fusce in velit non nibh maximus gravida vel et est. Nunc mollis dolor vel risus efficitur maximus. Donec sit amet nunc ut velit venenatis sodales. Nam non feugiat urna. Nam et dolor hendrerit, tempus urna ac, eleifend diam. Etiam justo leo, euismod ut magna et, semper porta nunc. Maecenas pharetra porttitor egestas. Maecenas rutrum odio nec dolor tincidunt, sed rhoncus ipsum pulvinar. Quisque id lacus vel leo pretium ullamcorper. Praesent tortor neque, volutpat vel dictum et, aliquam et enim. Integer semper eros ac augue molestie sollicitudin. Duis finibus, elit vestibulum consequat condimentum, tortor nibh auctor leo, id feugiat dolor mauris at mauris.",
  "Maecenas faucibus, nisi sed mattis pharetra, sem est aliquam enim, quis efficitur tellus est nec neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam mi tellus, laoreet sit amet mi et, tristique pretium elit. Nam ut tincidunt nunc. Cras vitae sapien lorem. In eu varius lacus. Cras eget congue ligula, ut vulputate odio. Donec ullamcorper turpis eget dolor lacinia finibus. Aliquam dapibus sem leo. Integer a nulla lorem. In et tellus id lacus semper hendrerit. Nulla eget convallis lacus, vitae semper mauris. Ut vel elit non elit tincidunt sodales eu ut dolor.",
  "Phasellus sollicitudin risus in ante porttitor, quis rhoncus lectus suscipit. Donec finibus pellentesque mauris. Ut sit amet euismod dui. Cras eros leo, pellentesque non nunc vel, malesuada finibus est. Aenean et ligula enim. Quisque congue sit amet purus id lobortis. Proin at fermentum est.",
  "Vestibulum malesuada neque nec dapibus feugiat. Donec vel tristique orci, eu pharetra lacus. Donec nulla ipsum, feugiat sit amet tincidunt sit amet, volutpat in tortor. Maecenas suscipit, erat eu faucibus sollicitudin, nisl eros semper nibh, non dictum odio turpis vitae tellus. Cras pellentesque, eros eget ultrices dictum, risus sapien condimentum dui, ut commodo magna enim eu ipsum. Donec semper risus quis suscipit fermentum. Praesent ac turpis aliquet, imperdiet nibh et, viverra nulla. Pellentesque neque enim, feugiat ut dapibus sit amet, consectetur in turpis. Sed dignissim purus nec efficitur sagittis. Nam ac tortor eget elit aliquam porttitor non non velit. Proin ut gravida urna. Nam condimentum aliquam est, eu vehicula leo feugiat et. Donec egestas lorem ac dui tempus feugiat. Vivamus quis dui et lorem placerat rutrum.",
  "Suspendisse eget ultricies augue, vel porta mi. Nunc vitae scelerisque nibh. Nullam iaculis eget magna a elementum. Aenean pretium tellus eu rutrum lobortis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed viverra bibendum vulputate. Aliquam et feugiat ante. Ut ac nibh gravida, fermentum libero non, iaculis felis.",
  "Suspendisse a interdum felis. Nam ipsum risus, eleifend vel volutpat at, feugiat sit amet lacus. Suspendisse potenti. Donec ut lacinia leo. Phasellus auctor pellentesque finibus. Suspendisse potenti. Aliquam et enim dapibus, sagittis augue tempor, egestas nunc. Sed malesuada porttitor orci sed dapibus. Vivamus eu enim dolor. Proin finibus metus sed ante placerat pulvinar. Suspendisse sed iaculis ligula. Donec ac magna vel ipsum consequat fermentum. Vestibulum posuere purus vitae pretium semper. Aliquam erat odio, pellentesque non ex ac, malesuada pharetra nibh. Integer semper ligula est, eu vehicula neque accumsan eget.",
  "Cras tempus ligula eu velit ultrices pretium. Ut lacinia tellus sit amet condimentum efficitur. Nam et arcu a lorem rhoncus gravida sed sit amet leo. In nec metus hendrerit, fermentum est non, ornare magna. Cras quis nibh eros. Praesent at dui at turpis rhoncus accumsan. Praesent ultricies mi semper diam congue tempor. Aenean aliquet turpis lacus, ut pharetra sapien efficitur eget. Sed non tempus neque, ac vestibulum lectus. Ut ac vulputate ipsum. Donec sollicitudin vulputate urna eu pulvinar.",
  "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam neque massa, suscipit vitae nibh vitae, rutrum lobortis purus. Aenean justo quam, posuere at interdum vitae, posuere vel nisi. Mauris pretium dictum tempor. Nullam ut rutrum felis, vel vestibulum eros. Ut ac commodo tellus. Sed vehicula nibh nec ipsum faucibus, eu convallis dolor fermentum. Suspendisse in nisl non leo auctor interdum. Donec nec pretium metus. Suspendisse mollis lectus in enim condimentum, at egestas enim consequat. Integer ac quam risus. Curabitur arcu magna, scelerisque sit amet dignissim non, pharetra eget mauris.",
  "Nulla pulvinar rhoncus ligula. Duis eros lectus, lobortis non efficitur nec, luctus vitae lectus. Nunc consectetur sapien a arcu lobortis, non suscipit velit interdum. Phasellus dui odio, scelerisque vitae quam quis, lacinia blandit nisl. Sed hendrerit pulvinar feugiat. Proin venenatis aliquet volutpat. Fusce risus turpis, pulvinar at ante sed, feugiat vulputate lorem.",
  "Aliquam imperdiet leo a vulputate facilisis. Nullam condimentum leo nibh, id pellentesque tellus mollis non. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ullamcorper ac lacus feugiat ultrices. Praesent at gravida augue. Phasellus lacus odio, placerat quis laoreet eu, gravida id elit. Nullam in sem fermentum, auctor velit vitae, aliquam est. Pellentesque vel tincidunt ex. Mauris congue libero id tempus consectetur. Pellentesque non feugiat risus. Pellentesque quis leo vehicula, blandit massa at, ultrices dui.",
  "Curabitur elit est, scelerisque sed erat sit amet, maximus gravida ante. Nam vel tortor quis nisi lobortis aliquet. Proin sed vestibulum lorem. In id laoreet tortor. Cras maximus arcu a auctor semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer tristique facilisis orci, eget rutrum nulla commodo malesuada. Etiam suscipit sed magna vitae blandit. Duis sed facilisis risus. Praesent eu egestas tortor. Cras vel ante sed dui pretium semper ut in neque. Curabitur ut magna at ex malesuada posuere. Sed luctus consequat est, sed consequat sem aliquam non.",
  "Donec urna neque, laoreet eu vehicula vel, suscipit at elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus aliquet vestibulum facilisis. Aliquam a est id mauris pretium interdum. In interdum venenatis molestie. Mauris bibendum placerat tortor. Ut aliquet, felis ut lacinia ullamcorper, orci nisl bibendum nulla, ut lacinia diam dolor sed est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec cursus quis nisi quis elementum. Nam ligula enim, vehicula sit amet nisi sit amet, pharetra sodales felis. Phasellus eget efficitur augue. Maecenas vitae risus odio.",
  "Mauris lacinia eleifend neque. Aliquam elit ante, viverra et felis non, efficitur molestie lorem. Duis pellentesque tellus eros, blandit volutpat sem ultrices sed. In hac habitasse platea dictumst. Nam fringilla id leo non luctus. Donec fringilla mauris non sapien imperdiet, ut efficitur diam vestibulum. Nunc non diam vulputate, egestas risus volutpat, semper lacus. Etiam vehicula, nisl in blandit hendrerit, tortor augue eleifend mi, ac aliquet quam dui vitae enim. Morbi dignissim commodo nulla, eget lacinia ipsum rhoncus sit amet. Donec luctus laoreet ex. Aliquam tincidunt justo eget lorem suscipit posuere. Duis pellentesque vel magna eu efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam hendrerit libero ut sapien volutpat luctus. Praesent quis luctus nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
  "Aenean bibendum tellus sapien, at sagittis elit faucibus in. Nulla facilisi. Vestibulum urna velit, dapibus sed ultricies sit amet, tempor id diam. Nulla vitae viverra purus. Pellentesque quis orci quam. Donec ut rhoncus mauris. Sed ut mauris nec tortor sollicitudin egestas in sit amet purus. Pellentesque gravida purus tincidunt magna euismod sodales.",
  "Suspendisse massa diam, feugiat in nulla vitae, congue laoreet nunc. Donec efficitur dapibus lectus ac interdum. Mauris facilisis, risus in efficitur sodales, risus nulla euismod enim, nec lobortis mi tortor at nisi. Aenean pretium neque eget est fringilla pharetra. Vestibulum arcu nibh, elementum nec feugiat ut, elementum vitae quam. Quisque porta tristique tortor. Cras aliquam diam sagittis tincidunt semper. Sed tincidunt justo facilisis tincidunt sollicitudin. Duis sed gravida purus.",
  "Nulla quis consectetur nisi. Nulla hendrerit fermentum magna, non hendrerit elit mattis porttitor. Vestibulum eu odio et odio imperdiet lacinia sit amet ac nibh. Ut id nibh mi. Pellentesque pulvinar arcu ac enim porta, eu porttitor leo commodo. Nullam imperdiet porttitor mi, quis laoreet velit egestas ornare. Curabitur vitae erat et dui consequat aliquet a id justo. Suspendisse sodales elit dui. Vivamus et nunc vulputate, hendrerit lorem sed, consequat tellus. Proin sit amet nunc diam.",
  "Fusce lacinia eget ex eu accumsan. Morbi aliquet justo vel ante condimentum, sit amet sagittis tortor semper. Etiam vestibulum eros felis, in dictum velit auctor eu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In hac habitasse platea dictumst. Praesent auctor ultricies lectus et tristique. Donec pretium urna purus. In rhoncus nisl et risus pharetra, ut semper erat cursus. Quisque arcu nunc, accumsan nec facilisis nec, porttitor vitae mi. Vivamus vel dictum odio, ac pharetra ipsum. Praesent at elit et nisl suscipit auctor ac sed neque. Quisque ac lectus ultricies, dignissim nisi quis, ultricies mauris. In venenatis condimentum sapien id aliquet. Etiam vitae tellus nunc.",
  "Donec pulvinar rhoncus augue, id dignissim nulla fringilla et. Proin nulla quam, gravida quis nisi eu, vestibulum scelerisque velit. Pellentesque aliquet imperdiet neque. Phasellus eu ullamcorper eros. Praesent vehicula enim eget dui fringilla placerat. Ut cursus eros ac est tincidunt dictum. In vitae suscipit lacus, a convallis erat. Curabitur et sodales nibh.",
  "Proin porta condimentum sem, vel scelerisque tortor ornare eu. Maecenas sit amet quam risus. Etiam urna eros, commodo quis leo eu, tempus fermentum ante. Aenean at nibh quam. Praesent elit ligula, mollis ac justo ut, sodales aliquam ipsum. Donec ante risus, facilisis nec gravida vitae, aliquam eu leo. Etiam vitae ante hendrerit, tincidunt arcu in, iaculis tortor. Nullam a arcu a erat semper malesuada. Aliquam erat volutpat. Maecenas nibh orci, accumsan quis neque eu, pretium gravida arcu. Quisque tempus faucibus libero nec dapibus. Aliquam at aliquam purus, sed venenatis dolor. In varius urna id ex malesuada lobortis. Praesent nec libero vel ipsum imperdiet ultricies. Phasellus sit amet velit urna.",
  "Sed eu diam gravida, imperdiet nibh imperdiet, fringilla diam. Nullam ut venenatis eros. Vestibulum elementum lectus a nunc vehicula ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam dignissim lacinia neque eget blandit. Sed fringilla diam sit amet elit semper, at rutrum diam cursus. Phasellus vestibulum, nunc at tempor cursus, nisl mauris imperdiet tellus, et consequat nunc eros quis leo. Nunc sodales tempus quam, ac tempus quam malesuada et. Pellentesque aliquet tincidunt risus, nec sollicitudin nibh. Curabitur posuere lorem urna, id auctor augue fermentum eget. Nullam vehicula, mi eu semper convallis, ex diam aliquam dolor, eget laoreet lacus tellus id tellus.",
  "Vestibulum risus urna, tempus condimentum elit et, ultricies sodales ante. Praesent ac quam ipsum. Nulla varius ex in nunc commodo vehicula eu ac sapien. Nam vestibulum dignissim blandit. Aliquam erat volutpat. Sed auctor porta tempor. Morbi ut nisl vel justo vulputate aliquet.",
  "Nam elementum tristique molestie. Suspendisse posuere velit ut dictum egestas. Duis ornare lobortis augue sollicitudin pharetra. Nunc sit amet odio sit amet neque fringilla lacinia a at est. Phasellus auctor lacus sit amet ligula imperdiet suscipit. Aliquam erat volutpat. Sed gravida ex nec nisi consequat vestibulum. Morbi congue, magna vitae vulputate ornare, leo justo pulvinar libero, at finibus odio dui in ante. Integer pharetra elit vitae nisi vestibulum hendrerit. Aliquam mattis turpis nec erat condimentum, nec bibendum dolor viverra. Nunc condimentum congue leo nec tempus. Vestibulum semper, est at condimentum efficitur, tortor massa imperdiet tortor, quis suscipit nisl lectus eu erat. Aenean volutpat blandit augue. Praesent mattis diam id nisi condimentum, vitae porttitor ligula placerat. Suspendisse pharetra vel neque eget porttitor. Nullam lacinia dignissim odio, ut porta ipsum euismod ac.",
  "Mauris vitae tellus neque. In hac habitasse platea dictumst. Vivamus sit amet lacus quis turpis blandit iaculis. Aliquam vel felis nec nulla pretium semper ut ut dui. Mauris sed arcu et metus commodo posuere. Donec ultrices nisl enim, in aliquam urna venenatis sed. Integer in auctor quam. Donec posuere eros elit. Cras pulvinar mattis tellus, cursus elementum dolor gravida a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum massa a urna egestas, et porttitor nunc suscipit",
];

const form = document.querySelector(".lorem-form");
const amount = document.getElementById("amount");
const lorem = document.querySelector(".lorem");
const randbtn = document.querySelector(".randbtn");
const clrscrnbtn = document.querySelector("#clrscrnbtn");

form.addEventListener("submit", function (e) {
  e.preventDefault(); // form elements tend to submit the value to a server and earse themselves. we want to retain it.
  const value = parseInt(amount.value); // Geting the value from the amount ID in the form of INT

  if (value < 0 || value > 49) {
    lorem.textContent = text[0];
  } else {
    let range = text.slice(0, value);
    range = range
      .map(function (item) {
        return item;
      })
      .join("\n\n");
    lorem.textContent = range;
  }
});

randbtn.addEventListener("click", function (f) {
  f.preventDefault();
  const random = Math.floor(Math.random() * 10); // Generating a random number
  let range = text.slice(0, random);
  range = range
    .map(function (item) {
      return item;
    })
    .join("\n\n");
  lorem.textContent = range;
  amount.value = random;
});

clrscrnbtn.addEventListener("click", function (g) {
  g.preventDefault();
  lorem.textContent = "";
  amount.value = "";
});

var tooltip = document.querySelector("#myTooltip");
var tooltiptext = document.querySelector(".tooltip");
var copyText = document.querySelector(".lorem");

function myFunction() {
  if (amount.value == "") {
    tooltip.innerHTML = "Nothing to copy :{";
  } else {
    tooltip.innerHTML = "Copy to clipboard?";
    navigator.clipboard.writeText(copyText.innerHTML);
  }
}

function disp() {
  if (amount.value == "" || amount.value == "0") {
    tooltip.innerHTML = "Nothing Copied :{";
  } else {
    tooltip.innerHTML = "Copied!";
  }
}
